apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    purpose: roboshop
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      purpose: roboshop
  template:
    metadata:
      labels:
        app: mysql
        purpose: roboshop
    spec:
      tolerations:
        - key: "purpose"
          operator: "Equal"
          value: "roboshop"
          effect: "PreferNoSchedule"
      containers:
        - name: mysql
          image: 826334059644.dkr.ecr.us-east-1.amazonaws.com/mysql_demo:latest
          ports:
          - containerPort: 3306
          resources:
            limits:
              cpu: 400m
              memory: 400Mi
            requests:
              cpu: 400m
              memory: 400Mi
          # env:
          # - name: MYSQL_ROOT_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       key: mysql-root-password
          #       name: mysql-secrets
          # - name: MYSQL_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       key: mysql-password
          #       name: mysql-secrets
          #       optional: true
        # - name: MYSQL_USER
        # - name: MYSQL_DATABASE
