apiVersion: v1
data:
  mysql-password: Um9ib1Nob3BAMQo=
  mysql-root-password: Um9ib1Nob3BAMQo=
kind: Secret
metadata:
  labels:
    app: mysql
  name: mysql-secrets
  namespace: roboshop
type: Opaque